/* Gemmer appens filer på telefonen, så den virker uden net. Versionen skifter, hver gang siden bygges om, og så hentes filerne igen. */
const CACHE = 'hiero-proto-392c117b0e';
const FILES = [ "./", "index.html", "manifest.webmanifest", "fonts/NewGardiner.ttf", "fonts/gentium-book-plus-latin-400-italic.woff2", "fonts/gentium-book-plus-latin-400-normal.woff2", "fonts/gentium-book-plus-latin-700-normal.woff2", "fonts/gentium-book-plus-latin-ext-400-italic.woff2", "fonts/gentium-book-plus-latin-ext-400-normal.woff2", "fonts/gentium-book-plus-latin-ext-700-normal.woff2", "fonts/gentium-book-plus-vietnamese-400-italic.woff2", "fonts/gentium-book-plus-vietnamese-400-normal.woff2", "fonts/gentium-book-plus-vietnamese-700-normal.woff2", "fonts/ibm-plex-mono-latin-400-normal.woff2", "fonts/ibm-plex-mono-latin-500-normal.woff2", "fonts/ibm-plex-mono-latin-ext-400-normal.woff2", "fonts/ibm-plex-mono-latin-ext-500-normal.woff2", "fonts/ibm-plex-mono-vietnamese-400-normal.woff2", "fonts/ibm-plex-mono-vietnamese-500-normal.woff2", "fonts/ibm-plex-sans-latin-400-normal.woff2", "fonts/ibm-plex-sans-latin-500-normal.woff2", "fonts/ibm-plex-sans-latin-600-normal.woff2", "fonts/ibm-plex-sans-latin-ext-400-normal.woff2", "fonts/ibm-plex-sans-latin-ext-500-normal.woff2", "fonts/ibm-plex-sans-latin-ext-600-normal.woff2", "fonts/ibm-plex-sans-vietnamese-400-normal.woff2", "fonts/ibm-plex-sans-vietnamese-500-normal.woff2", "fonts/ibm-plex-sans-vietnamese-600-normal.woff2", "fonts/noto-sans-egyptian-hieroglyphs-egyptian-hieroglyphs-400-normal.woff2", "fonts/noto-sans-egyptian-hieroglyphs-latin-400-normal.woff2", "fonts/noto-sans-egyptian-hieroglyphs-latin-ext-400-normal.woff2", "icons/icon-192.png", "icons/icon-512.png", "icons/icon-maskable-512.png", "vendor/sqlite-wasm/index.mjs", "vendor/sqlite-wasm/sqlite3.wasm" ];
self.addEventListener('install', e => { e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then(hit => hit || fetch(e.request).catch(() => e.request.mode === 'navigate' ? caches.match('index.html') : Response.error())));
});
